### ISSUE TITLE
Storefront sticky header issue

### ISSUE THREAD

**Issue by bryceadams** [Recipe-Hero/Recipe-Hero#108]
When Storefront Designer is used and the sticky header is set, it looks like this:

![see screen shot](https://cldup.com/148r63XXwW-3000x3000.png)

Without:

![see screen shot](https://cldup.com/HSEbgCQFe2-3000x3000.png)

Will look into it to see if this can be changed so the lightbox is always at the front.

**Comment by bradleysa** [comment]
Hey Bryce,
I wanted to check in, and see if you have an update on this little bug.
Recipe Hero 1.0.9
Storefront Designer 1.4.0
Storefront 1.2.5

Thank you very much.
Bradley

**Comment by bryceadams** [comment]
Hey @bradleysa,

Sorry for the delay!

Just checked and I think the best way would be for you to add the following custom CSS:

```
.mfp-wrap.mfp-gallery { z-index: 10000 !important; }
```

Let me know if that does it for you :)

**Comment by bradleysa** [comment]
Yes, that works.
I look forward to publishing tasty recipes.

**Comment by bryceadams** [comment]
:)
