### ISSUE TITLE
Fractions don't work when numerator is 1

### ISSUE THREAD

**Issue by bradleysa** [Recipe-Hero/Recipe-Hero#130]
When listing out ingredients, fractions do not work when the numerator is 1. For example, "1/2 cup" will display as "1 cup."

Fractions appear to work correctly when the numerator is 2 or 3, for example.

Tested using version 1.0.9, and no other active plugins.
![ingredients-admin](https://cloud.githubusercontent.com/assets/2933792/6101712/b2ca8b10-afdd-11e4-8ef5-b2a283ccfbfc.png)
![ingredients-display](https://cloud.githubusercontent.com/assets/2933792/6101713/b2ccab20-afdd-11e4-960b-8e038915b843.png)

**Comment by bryceadams** [comment]
Hey @bradleysa - hmm, strange bug! Thanks for letting me know - added to todo list.

**Comment by bradleysa** [comment]
Yeah, that does seem strange :) 
I've got a tasty recipe basically ready to roll.
Thanks Bryce!

**Comment by bryceadams** [comment]
:) Seems to be related to how `_n()` handles fractions - http://codex.wordpress.org/Function_Reference/_n

Looking into a solution now.

**Comment by bryceadams** [comment]
Ah, it's quite frustrating. So I will need to convert the ingredient quantity to decimal and then based on it being a decimal amount < 2, convert to fraction and then conditionally show plural.

Will get to it as soon as I have some spare time :) Bit weird but for now maybe try 2/4 instead while I think of a better way to handle it.

**Comment by bradleysa** [comment]
Oh wow, that definitely sounds complicated. Thanks for the potential workaround, however I prefer to wait patiently rather than substitute either 4/6 or .67 for 2/3 cup, or trying 1/8 teaspoon.

**Comment by bradleysa** [comment]
Have you been able to make any headway on this one?

**Comment by bryceadams** [comment]
Will push to wp.org now

**Comment by bradleysa** [comment]
You nailed it! Thanks so much for making this happen. Recipe Hero is the section of my website I'm most excited about expanding. More delicious jam recipes are on the way!

**Comment by bryceadams** [comment]
@bradleysa more to come as soon as I get time! :)
